# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-29 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=30, unique=True, verbose_name='\u6635\u79f0')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='\u540d\u5b57')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='\u59d3')),
                ('email', models.EmailField(blank=True, max_length=100, unique=True, verbose_name='\u90ae\u7bb1')),
                ('is_staff', models.BooleanField(default=False, help_text='\u662f\u5426\u80fd\u591f\u767b\u5f55\u7ba1\u7406\u540e\u53f0', verbose_name='\u662f\u5426\u804c\u5458')),
                ('is_active', models.BooleanField(default=True, verbose_name='\u662f\u5426\u6fc0\u6d3b')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='\u52a0\u5165\u65e5\u671f')),
                ('avatar_url', models.ImageField(blank=True, default='avatar/default_avatar_big.png', max_length=200, null=True, upload_to='avatar/%Y/%m', verbose_name='\u5934\u50cf220*220')),
                ('avatar_middle_thumbnall', models.ImageField(blank=True, default='avatar/default_avatar_middle.png', max_length=200, null=True, upload_to='avatar/%Y/%m', verbose_name='\u5934\u50cf140*140')),
                ('avatar_small_thumbnall', models.ImageField(blank=True, default='avatar/default_avatar_small.png', max_length=200, null=True, upload_to='avatar/%Y/%m', verbose_name='\u5934\u50cf70*70')),
                ('qq', models.CharField(blank=True, max_length=15, null=True, verbose_name='QQ\u53f7\u7801')),
                ('mobile', models.CharField(blank=True, max_length=15, null=True, verbose_name='\u624b\u673a\u53f7\u7801')),
                ('valid_email', models.SmallIntegerField(choices=[(0, '\u5426'), (1, '\u662f')], default=0, verbose_name='\u662f\u5426\u9a8c\u8bc1\u90ae\u7bb1')),
                ('company_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='\u516c\u53f8\u540d')),
                ('position', models.CharField(blank=True, max_length=15, null=True, verbose_name='\u804c\u4f4d\u540d')),
                ('discription', models.TextField(blank=True, null=True, verbose_name='\u4e2a\u4eba\u4ecb\u7ecd')),
                ('city', models.CharField(blank=True, max_length=8, null=True, verbose_name='\u57ce\u5e02')),
                ('province', models.CharField(blank=True, max_length=8, null=True, verbose_name='\u7701\u4efd')),
                ('index', models.IntegerField(blank=True, default=999, null=True, verbose_name='\u6392\u5217\u987a\u5e8f(\u4ece\u5c0f\u5230\u5927)')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'user_profile',
                'verbose_name': '\u7528\u6237',
                'verbose_name_plural': '\u7528\u6237',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='\u6807\u9898')),
                ('type', models.CharField(choices=[('ACTIVITY', '\u5b98\u65b9\u6d3b\u52a8'), ('NEWS', '\u65b0\u95fb\u54a8\u8be2'), ('DISCUSS', '\u6280\u672f\u4ea4\u6d41')], default='ACTIVITY', max_length=8, verbose_name='\u6587\u7ae0\u7c7b\u578b')),
                ('data_publish', models.DateTimeField(auto_now_add=True, verbose_name='\u53d1\u5e03\u65f6\u95f4')),
                ('is_active', models.BooleanField(default=True, verbose_name='\u662f\u5426\u53d1\u5e03')),
                ('content', models.TextField(blank=True, null=True, verbose_name='\u6587\u7ae0\u5185\u5bb9')),
            ],
            options={
                'db_table': 'article',
                'verbose_name': '\u6587\u7ae0',
                'verbose_name_plural': '\u6587\u7ae0',
            },
        ),
        migrations.CreateModel(
            name='KeyWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True, verbose_name='\u5173\u952e\u5b57')),
            ],
            options={
                'db_table': 'keywords',
                'verbose_name': '\u5173\u952e\u5b57',
                'verbose_name_plural': '\u5173\u952e\u5b57',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='article_keywords',
            field=models.ManyToManyField(to='common.KeyWord'),
        ),
    ]
