# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 15:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=30, unique=True, verbose_name='\u6635\u79f0')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='\u540d\u5b57')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='\u59d3')),
                ('email', models.EmailField(blank=True, max_length=100, unique=True, verbose_name='\u90ae\u7bb1')),
                ('is_staff', models.BooleanField(default=False, help_text='\u662f\u5426\u80fd\u591f\u767b\u5f55\u7ba1\u7406\u540e\u53f0', verbose_name='\u662f\u5426\u804c\u5458')),
                ('is_active', models.BooleanField(default=True, verbose_name='\u662f\u5426\u6fc0\u6d3b')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='\u52a0\u5165\u65e5\u671f')),
                ('avatar_url', models.ImageField(blank=True, default='avatar/default_avatar_big.png', max_length=200, null=True, upload_to='avatar/%Y/%m', verbose_name='\u5934\u50cf220*220')),
                ('avatar_middle_thumbnall', models.ImageField(blank=True, default='avatar/default_avatar_middle.png', max_length=200, null=True, upload_to='avatar/%Y/%m', verbose_name='\u5934\u50cf140*140')),
                ('avatar_small_thumbnall', models.ImageField(blank=True, default='avatar/default_avatar_small.png', max_length=200, null=True, upload_to='avatar/%Y/%m', verbose_name='\u5934\u50cf70*70')),
                ('qq', models.CharField(blank=True, max_length=15, null=True, verbose_name='QQ\u53f7\u7801')),
                ('mobile', models.CharField(blank=True, max_length=15, null=True, verbose_name='\u624b\u673a\u53f7\u7801')),
                ('valid_email', models.SmallIntegerField(choices=[(0, '\u5426'), (1, '\u662f')], default=0, verbose_name='\u662f\u5426\u9a8c\u8bc1\u90ae\u7bb1')),
                ('company_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='\u516c\u53f8\u540d')),
                ('position', models.CharField(blank=True, max_length=15, null=True, verbose_name='\u804c\u4f4d\u540d')),
                ('discription', models.TextField(blank=True, null=True, verbose_name='\u4e2a\u4eba\u4ecb\u7ecd')),
                ('city', models.CharField(blank=True, max_length=8, null=True, verbose_name='\u57ce\u5e02')),
                ('province', models.CharField(blank=True, max_length=8, null=True, verbose_name='\u7701\u4efd')),
                ('index', models.IntegerField(blank=True, default=999, null=True, verbose_name='\u6392\u5217\u987a\u5e8f(\u4ece\u5c0f\u5230\u5927)')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'user_profile',
                'verbose_name': '\u7528\u6237',
                'verbose_name_plural': '\u7528\u6237',
            },
        ),
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='\u7f51\u7ad9\u5e7f\u544a')),
                ('discription', models.CharField(max_length=200, verbose_name='\u5e7f\u544a\u63cf\u8ff0')),
                ('img', models.ImageField(upload_to='ad/%Y/%m', verbose_name='\u5e7f\u544a\u56fe\u7247\u5730\u5740')),
                ('callback_url', models.URLField(blank=True, null=True, verbose_name='\u5e7f\u544a\u5730\u5740')),
                ('index', models.IntegerField(default=999, verbose_name='\u5e7f\u544a\u6392\u5e8f')),
            ],
            options={
                'ordering': ['index', 'id'],
                'db_table': 'ad',
                'verbose_name': '\u5e7f\u544a',
                'verbose_name_plural': '\u5e7f\u544a',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='\u6807\u9898')),
                ('type', models.CharField(choices=[('ACTIVITY', '\u5b98\u65b9\u6d3b\u52a8'), ('NEWS', '\u65b0\u95fb\u54a8\u8be2'), ('DISCUSS', '\u6280\u672f\u4ea4\u6d41')], default='ACTIVITY', max_length=8, verbose_name='\u6587\u7ae0\u7c7b\u578b')),
                ('data_publish', models.DateTimeField(auto_now_add=True, verbose_name='\u53d1\u5e03\u65f6\u95f4')),
                ('is_active', models.BooleanField(default=True, verbose_name='\u662f\u5426\u53d1\u5e03')),
                ('content', models.TextField(blank=True, null=True, verbose_name='\u6587\u7ae0\u5185\u5bb9')),
            ],
            options={
                'db_table': 'article',
                'verbose_name': '\u6587\u7ae0',
                'verbose_name_plural': '\u6587\u7ae0',
            },
        ),
        migrations.CreateModel(
            name='CareerCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u8bfe\u7a0b\u540d\u79f0')),
                ('short_name', models.CharField(max_length=10, unique=True, verbose_name='\u82f1\u6587\u7b80\u5199')),
                ('image', models.ImageField(upload_to='course/%Y/%m', verbose_name='\u56fe\u7247')),
                ('discription', models.TextField(verbose_name='\u63cf\u8ff0')),
                ('student_count', models.IntegerField(default=0, verbose_name='\u5b66\u751f\u6570\u91cf')),
                ('market_page_url', models.URLField(blank=True, null=True, verbose_name='\u8425\u9500\u9875\u9762\u5730\u5740')),
                ('total_price', models.DecimalField(decimal_places=1, default=0, max_digits=7, verbose_name='\u8bfe\u7a0b\u4ef7\u683c')),
                ('discount', models.DecimalField(decimal_places=2, default=1, max_digits=3, verbose_name='\u6298\u6263')),
                ('click_count', models.IntegerField(default=0, verbose_name='\u70b9\u51fb\u6570\u91cf')),
                ('index', models.IntegerField(default=999, verbose_name='\u6392\u5e8f')),
            ],
            options={
                'ordering': ['-id'],
                'db_table': 'career_course',
                'verbose_name': '\u804c\u4e1a\u8bfe\u7a0b',
                'verbose_name_plural': '\u804c\u4e1a\u8bfe\u7a0b',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u8bfe\u7a0b\u540d\u79f0')),
                ('image', models.ImageField(upload_to='course/%Y/%m', verbose_name='\u8bfe\u7a0b\u56fe\u7247')),
                ('discription', models.TextField(blank=True, null=True, verbose_name='\u63cf\u8ff0')),
                ('index', models.IntegerField(default=999, verbose_name='\u987a\u5e8f')),
                ('is_active', models.BooleanField(default=True, verbose_name='\u662f\u5426\u6fc0\u6d3b')),
                ('date_publish', models.DateTimeField(auto_now_add=True, verbose_name='\u53d1\u5e03\u65f6\u95f4')),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('need_days', models.IntegerField(default=5, verbose_name='\u5b66\u4e60\u65f6\u95f4/h')),
                ('need_days_base', models.IntegerField(default=3, verbose_name='\u6709\u57fa\u7840\u7684\u5b66\u4e60\u65f6\u95f4/h')),
                ('student_count', models.IntegerField(default=0, verbose_name='\u5b66\u751f\u4eba\u6570')),
                ('favorite_count', models.IntegerField(default=0, verbose_name='\u6536\u85cf\u6570\u91cf')),
                ('click_count', models.IntegerField(default=0, verbose_name='\u70b9\u51fb\u6570\u91cf')),
                ('is_voince', models.BooleanField(default=False, verbose_name='\u662f\u5426\u65b0\u624b\u8bfe\u7a0b')),
                ('is_homeshow', models.BooleanField(default=False, verbose_name='\u662f\u5426\u663e\u793a\u9996\u9875')),
                ('is_required', models.BooleanField(default=True, verbose_name='\u662f\u5426\u5fc5\u4fee')),
            ],
            options={
                'ordering': ['index', 'id'],
                'db_table': 'course',
                'verbose_name': '\u8bfe\u7a0b',
                'verbose_name_plural': '\u8bfe\u7a0b',
            },
        ),
        migrations.CreateModel(
            name='CourseResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u540d\u79f0')),
                ('download_url', models.FileField(upload_to='course/%Y/%m', verbose_name='\u4e0b\u8f7d\u5730\u5740')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Course', verbose_name='\u8bfe\u7a0b')),
            ],
            options={
                'db_table': 'course_resourse',
                'verbose_name': '\u8bfe\u7a0b\u8d44\u6e90',
                'verbose_name_plural': '\u8bfe\u7a0b\u8d44\u6e90',
            },
        ),
        migrations.CreateModel(
            name='KeyWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True, verbose_name='\u5173\u952e\u5b57')),
            ],
            options={
                'db_table': 'keywords',
                'verbose_name': '\u5173\u952e\u5b57',
                'verbose_name_plural': '\u5173\u952e\u5b57',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u540d\u79f0')),
                ('video_url', models.CharField(max_length=200, verbose_name='\u89c6\u9891\u5730\u5740')),
                ('video_length', models.IntegerField(verbose_name='\u89c6\u9891\u957f\u5ea6')),
                ('play_count', models.IntegerField(default=0, verbose_name='\u64ad\u653e\u6b21\u6570')),
                ('share_count', models.IntegerField(default=0, verbose_name='\u5206\u4eab\u6b21\u6570')),
                ('index', models.IntegerField(default=999, verbose_name='\u64ad\u653e\u987a\u5e8f')),
                ('is_popup', models.BooleanField(default=False, verbose_name='\u662f\u5426\u5f39\u51fa\u652f\u4ed8\u7a97\u53e3')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Course', verbose_name='\u8bfe\u7a0b')),
            ],
            options={
                'ordering': ['index', 'id'],
                'db_table': 'lesson',
                'verbose_name': '\u7ae0\u8282',
                'verbose_name_plural': '\u7ae0\u8282',
            },
        ),
        migrations.CreateModel(
            name='LessonResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u540d\u79f0')),
                ('download_url', models.FileField(upload_to='lesson/%Y/%m', verbose_name='\u4e0b\u8f7d\u5730\u5740')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Lesson', verbose_name='\u7ae0\u8282')),
            ],
            options={
                'db_table': 'lesson_resourse',
                'verbose_name': '\u7ae0\u8282\u8d44\u6e90',
                'verbose_name_plural': '\u7ae0\u8282\u8d44\u6e90',
            },
        ),
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='\u6807\u9898')),
                ('discription', models.CharField(blank=True, max_length=200, null=True, verbose_name='\u63cf\u8ff0')),
                ('callback_url', models.URLField(verbose_name='\u94fe\u63a5')),
                ('image', models.ImageField(blank=True, null=True, upload_to='link/%Y/%m', verbose_name='\u56fe\u7247\u8def\u5f84')),
            ],
            options={
                'db_table': 'links',
                'verbose_name': '\u53cb\u60c5\u94fe\u63a5',
                'verbose_name_plural': '\u53cb\u60c5\u94fe\u63a5',
            },
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u9636\u6bb5\u540d\u79f0')),
                ('discription', models.TextField(blank=True, null=True, verbose_name='\u63cf\u8ff0')),
                ('index', models.IntegerField(default=999, verbose_name='\u987a\u5e8f')),
                ('is_try', models.BooleanField(default=False, verbose_name='\u662f\u5426\u8bd5\u5b66')),
                ('career_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.CareerCourse', verbose_name='\u804c\u4e1a\u8bfe\u7a0b')),
            ],
            options={
                'ordering': ['index', 'id'],
                'db_table': 'stage',
                'verbose_name': '\u9636\u6bb5',
                'verbose_name_plural': '\u9636\u6bb5',
            },
        ),
        migrations.CreateModel(
            name='StageCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Course')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Stage')),
            ],
            options={
                'ordering': ['id'],
                'db_table': 'stage_course',
                'verbose_name': '\u9636\u6bb5-\u8bfe\u7a0b',
                'verbose_name_plural': '\u9636\u6bb5-\u8bfe\u7a0b',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='search_keywords',
            field=models.ManyToManyField(to='common.KeyWord', verbose_name='\u5c0f\u8bfe\u7a0b\u641c\u7d22\u5173\u952e\u5b57'),
        ),
        migrations.AddField(
            model_name='course',
            name='stages',
            field=models.ManyToManyField(through='common.StageCourse', to='common.Stage', verbose_name='\u9636\u6bb5'),
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u6388\u8bfe\u8001\u5e08'),
        ),
        migrations.AddField(
            model_name='careercourse',
            name='search_keywords',
            field=models.ManyToManyField(to='common.KeyWord', verbose_name='\u641c\u7d22\u5173\u952e\u5b57'),
        ),
        migrations.AddField(
            model_name='article',
            name='article_keywords',
            field=models.ManyToManyField(to='common.KeyWord'),
        ),
    ]
