# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-29 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='\u7f51\u7ad9\u5e7f\u544a')),
                ('discription', models.CharField(max_length=200, verbose_name='\u5e7f\u544a\u63cf\u8ff0')),
                ('img', models.ImageField(upload_to='ad/%Y/%m', verbose_name='\u5e7f\u544a\u56fe\u7247\u5730\u5740')),
                ('callback_url', models.URLField(blank=True, null=True, verbose_name='\u5e7f\u544a\u5730\u5740')),
                ('index', models.IntegerField(default=999, verbose_name='\u5e7f\u544a\u6392\u5e8f')),
            ],
            options={
                'ordering': ['index', 'id'],
                'db_table': 'ad',
                'verbose_name': '\u5e7f\u544a',
                'verbose_name_plural': '\u5e7f\u544a',
            },
        ),
    ]
